<?php echo '<h1>' .$this->escapeHtml(ucfirst($this->category)) . '</h1>';

if($this->lists instanceof \Zend\Db\ResultSet\ResultSet){
    ?>
    <table>
        <tr>
            <th>Item</th>
            <th>Price</th>
            <th></th>
            <th>Posted</th>
        </tr>
    <?php
        foreach ($this->lists as $list) {
            ?>
        <tr style="background-color:<?php echo $this->cycle(array("#FAC769","#f9A770","#FAAE58"))->next(); ?>">
            <td><?php echo $this->escapeHtml($list["title"]);?></td>
            <td><a href="/market/view/item/<?php echo $list["listings_id"];?>"><?php echo $this->escapeHtml((float)$list["price"]);?></a></td>
            <td></td>
            <td><?php echo $this->escapeHtml($list["date_created"]);?></td>
        </tr>
        <?php }?>
    </table>
    <?php
}


?>


