<?php
if($item){

    ?>
    <h3><?php echo $this->escapeHtml(ucwords($item->title)); ?></h3>
    <div style="width: 250px;float:left;">
        <?php if($item->photo_filename):?>
            <img src="<?php echo $this->item->photo_filename;?>" />
        <?php else:?>
            No image
        <?php endif; ?>
    </div>
    <div style="width: 400px;float:left;">
        <b>Contacts</b><br />
        <?php echo $this->escapeHtml(ucwords($item->contact_name)); ?><br />
        <?php echo $this->escapeHtml(ucwords($item->contact_email)); ?><br />
        <?php echo $this->escapeHtml(ucwords($item->contact_phone)); ?><br />
        <b>Posting Details</b><br />
        <?php echo $this->escapeHtml(ucwords($item->date_created)); ?><br />
        Price: <?php echo $this->escapeHtml(ucwords($item->price)); ?><br />
        City: <?php echo $this->escapeHtml(ucwords($item->city)); ?> , <?php  echo $this->escapeHtml(ucwords($item->country)); ?><br />
        Description: <?php echo $this->escapeHtml(ucwords($item->description)); ?><br />
    </div>
<?php

}else{
    echo "No recent posting";
}